class MainPageLocators:
    NAME_FIELD = ("id", "name-input")
    PASSWORD_FIELD = ("xpath", "//input[@type='password']")
    MILK_CHECKBOX = ("css selector", 'input[value="Milk"]')
    COFFEE_CHECKBOX = ("id", 'drink3')
    RBUTTON_YELLOW = ("xpath", '//*[@id="color3"]')
    AUTO_TYPE_MENU = ("css selector", 'select[data-testid="automation"]')
    AUTO_TYPE = ("xpath", '//option[@data-testid="automation-yes"]')
    EMAIL_FIELD = ("id", 'email')
    MESSAGE_FIELD = ("xpath", '//textarea[@id="message"]')
    SUBMIT_BUTTON = ("xpath", "//button[@class='custom_btn btn_hover']")
    TOOLS_AREA = ("xpath", '//*[@id="feedbackForm"]/ul')
