name: Run Tests in Docker (API + UI)

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Start Backend
        working-directory: ./api_tests/backend
        run: |
          docker-compose up --build -d
          sleep 10

      - name: Check backend health
        run: |
          curl --retry 5 --retry-delay 3 --retry-all-errors http://localhost:8000/healthcheck

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist allure-pytest

      - name: Run API Tests
        run: |
          python -m pytest api_tests/tests/ \
            -n auto \
            --alluredir=./allure-results

      - name: Run UI Tests
        run: |
          python -m pytest ui_tests/tests/ \
            -n auto \
            --html=report.html \
            --self-contained-html \
            --alluredir=./allure-results

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            report.html
            ./allure-results/

      - name: Stop Backend
        if: always()
        working-directory: ./api_tests/backend
        run: docker-compose down