name: Parallel Selenium Tests with Allure

on:
  push:
    branches: [ui_tests]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ui_tests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-xdist selenium pytest-html allure-pytest

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo rm -f /usr/bin/chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run tests with Allure
        run: |
          rm -rf ./allure-results || true
          python -m pytest tests/ \
            -n auto \
            --html=report.html \
            --self-contained-html \
            --alluredir=./allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: ./allure-results

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-html-report
          path: report.html